pipeline {
 agent none
 stages {
  stage('Run Tests') {
   parallel {
    stage('Test On Windows') {
     agent any
     steps {
      sh "echo windows tests pass"
     }
    }
    stage('Test On Linux') {
     agent any
     steps {
      sh "echo linux tests pass"
     }
    }
   }
  }
 }
}